sudo: true

services:
    - docker

language:
    - php

php:
    - 7.1.1

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

before_install:
    - sudo /etc/init.d/mysql stop
    - echo "WP_VERSION=4.7.3"

install:
    - bin/up -d

script:
    - source bin/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh