sudo: required

language:
    - php

php:
    - 7.1.3

node_js:
    - stable

env:
    - WP_VERSION=latest WP_MULTISITE=0

install:
    - sudo apt-get install -y libxml2-utils
    - export TRAVIS_PHPUNIT_CONFIG=${TRAVIS_BUILD_DIR}/wp-tests/phpunit.xml.dist
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

deploy:
    - provider: script
      script: bin/deploy.sh
      on:
        branch: master