sudo: true

services:
    - docker

language:
    - php

php:
    - 7.1.1

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=0

before_install:
    - sudo /etc/init.d/mysql stop
    - echo "WP_VERSION=4.7.3"

install:
    - bin/up
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone -b feature/docker https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh