version: '2'

services:
    mysql:
        image: mariadb:10.1.21
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: wordpress # Must match WP_DB_NAME
            MYSQL_USER: wordpress # Must match WP_DB_USER
            MYSQL_PASSWORD: wordpress # Must match WP_DB_PASSWORD

    redis:
        image: redis:3.2.8-alpine
        ports:
            - 6379:6379
        volumes:
            - redis:/data

    php:
        image: xwpco/wordpress-alpine
        links:
            - mysql
            - redis
        volumes:
            - ./wordpress:/var/www/html/wordpress
            - ./wp-content:/var/www/html/wp-content
            - ./wp-config:/var/www/html/wp-config:ro
            - ./wp-tests:/var/www/html/wp-tests
        environment:
            WP_DB_HOST: mysql
            WP_DB_NAME: wordpress # Must match MYSQL_DATABASE
            WP_DB_USER: wordpress # Must match MYSQL_USER
            WP_DB_PASSWORD: wordpress # Must match MYSQL_PASSWORD
            WP_THEME_NAME: twentyseventeen
            WP_DOMAIN: wp.local
            WP_ADMIN_USER: wordpress
            WP_ADMIN_PASSWORD: wordpress
            WP_ADMIN_EMAIL: dev@wp.local
            WP_VERSION: 4.7.3
            WP_TITLE: "WP Docker"
            WP_DEBUG: 1
            XDEBUG_CONFIG: remote_host=127.0.0.1
            PHP_IDE_CONFIG: serverName=wp.local

    nginx:
        image: nginx:1.11.10-alpine
        volumes:
            - ./wordpress:/var/www/html/wordpress:ro
            - ./wp-content:/var/www/html/wp-content:ro
            - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/ssl:/etc/ssl
        links:
            - php
        ports:
            - 80:80
            - 443:443

volumes:
    mysql:
    redis:
